# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

username: admin
password: admin
# skip-verify: true
insecure: true
port: 57400
timeout: 10s
encoding: json_ietf

targets:
  SR-1x-92S:57400:
    subscriptions:
      - sros_port_oper_state
      - sros_port_stats
      - sros_port_traffic_rate
      - sros_if_stats
      - sros_if_delay
      - sros_bgp_anysec_peer
      - sros_bgp_anysec_sec_termination_policy
  SR-1se:57400:
    subscriptions:
      - sros_port_oper_state
      - sros_port_stats
      - sros_port_traffic_rate
      - sros_if_stats
      - sros_if_delay
      - sros_bgp_anysec_peer
      - sros_bgp_anysec_sec_termination_policy
  SR-2se:57400:
      subscriptions:
      - sros_port_oper_state
      - sros_port_stats
      - sros_port_traffic_rate
      - sros_if_stats
      - sros_if_delay
  SR-7s:57400:
    subscriptions:
      - sros_port_oper_state
      - sros_port_stats
      - sros_port_traffic_rate
      - sros_if_stats
      - sros_if_delay


subscriptions:

  sros_port_oper_state:
    paths:
      - /state/port[port-id=*]/oper-state
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_port_stats:
    paths:
      - /state/port[port-id=*]/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_port_traffic_rate:
    paths:
      - /state/port[port-id=*]/ethernet/oper-speed
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_if_stats:
    paths:
      - /state/router[router-name=Base]/interface[interface-name=*]/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s


  sros_if_delay:
    paths:
      - /state/router[router-name=Base]/interface[interface-name=*]/if-attribute/delay
    mode: stream
    stream-mode: sample
    sample-interval: 5s


  sros_bgp_anysec_peer:
    paths:
      - /state/anysec/tunnel-encryption/encryption-group[group-name=*]/peer[peer-ip-address=*]
    mode: stream
    stream-mode: sample
    sample-interval: 5s 

  sros_bgp_anysec_sec_termination_policy:
    paths:
      - /state/anysec/tunnel-encryption/security-termination-policy[policy-name=*]
    mode: stream
    stream-mode: sample
    sample-interval: 5s 






outputs:
  prom:
    type: prometheus
    listen: :9273
    path: /metrics
    metric-prefix: gnmic
    append-subscription-name: true
    export-timestamps: true
    debug: false
    event-processors:
      - trim-prefixes
      - up-down-map
  # stdout:
  #   type: file
  #   file-type: stdout
  #   event-processors:
  #     - proc-convert-strings-to-int
  #     - trim-prefixes

processors:
  trim-prefixes:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - path-base:
            apply-on: "name"
  up-down-map:
    event-strings:
      value-names:
        - oper-state
      transforms:
        - replace:
            apply-on: "value"
            old: "up"
            new: "1"
        - replace:
            apply-on: "value"
            old: "down"
            new: "0"
